### ISSUE TITLE
--u option for uninstall feature request

### ISSUE THREAD

**Issue by capaj** [mirek/node-unused-deps#2]
[npm-check-updates](https://www.npmjs.com/package/npm-check-updates) has a -u option where without the option, it would only list dependencies which are out of date. With -u option it would change the package.json as well.
So I would like it if this could behave the same.

Thanks in advance for your consideration.

**Comment by mirek** [comment]
Thanks for the report. I agree it would be nice to have, but I think cons are:
- the library would gain too much weight to support it
- it's impossible to determine unused dependencies with 100% accuracy in nodejs and the output should always be inspected manually; you wouldn't want to create grunt task with it for example. it's used much less frequently than npm-check-updates.
- the output is in shell format so it's trivial to run `unused-deps | sh` which does exactly what you want

**Comment by capaj** [comment]
@mirek I don't want to create a grunt task. I just wanted to save some extra work.

**Comment by mirek** [comment]
Ok, got it, use `unused-deps | sh`.
